apiVersion: v1
kind: Service
metadata:
  name: cybersecuritytraining
spec:
  selector:
    app: cybersecuritytraining
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8003
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybersecuritytraining
spec:
  selector:
    matchLabels:
      app: cybersecuritytraining
  replicas: 1
  template:
    metadata:
      labels:
        app: cybersecuritytraining
    spec:
      containers:
      - name: cybersecuritytraining
        image: cybersecuritytraining
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003